[obstacles]
obstacle1 = 9,1
obstacle2 = 8,4
obstacle3 = 1,6
obstacle4 = 6,8
obstacle5 = 14,10
obstacle6 = 4,14
obstacle7 = 16,15

[startZones]
A1 = 6,19
A2 = 9,19
A3 = 12,19

[transitZones]
# (: x,y,capacité)
zone1 = 12,10,1
zone2 = 12,9,1
zone3 = 9,10,1
zone4 = 9,9,1

[exitZones]
# Positions des zones de sortie (portes)
porte1 = 4,0
porte2 = 6,0
porte3 = 14,0
porte4 = 16,0

[goals]
# Points de livraison finaux (entre les portes)
Z1 = 5,0
Z2 = 15,0

[rechargeZones]
# Stations de recharge (haut de la grille, zone centrale)
R1 = 1,8
R2 = 1,12



